version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
#      - image: circleci/node:8.9
    steps:
#      - checkout
      - run:
          name: Test
          command: npm test
  lint:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: ESLint
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build