version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: NODE_ENV=development npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
  test:
    - attach_workspace:
        at: ~/project
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Test
          command: ls
#  lint:
#    working_directory: ~/project
#    docker:
#      - image: circleci/node:8.9
#    steps:
#      - checkout
#      - run:
#          name: ESLint
#          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
#      - lint:
#          requires:
#            - build